POST http://127.0.0.1:8080/a/?url=http%3A%2F%2Fgoogle.com%2F%3Fq%3Dgolang
Content-Type: application/json

{}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###
